apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow
  labels:
    type: local
spec:
  storageClassName: "manual"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: airflow
  hostPath:
    path: "/mnt/airflow"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
