apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-latest
  labels:
    type: local
spec:
  storageClassName: "manual"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: data-airflow-postgresql-0
  hostPath:
    path: "/mnt/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-airflow-postgresql-0
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
